Fix Travis CI error
Travis is running an older version of Bundler that causes the following error to be thrown.

``` ruby
NoMethodError: undefined method `spec' for nil:NilClass
```

Upgrading the bundler gem fixed it.